### ISSUE TITLE
Cannot install this site

### ISSUE THREAD

**Issue by xFlum3** [kerero/israel-alerts-map#1]
Hey, I want to self host the site but cannot start the site, can you please explain how to self host it ?

**Comment by kerero** [comment]
Hi, you need to 

1. either use the dev container defined in `.devcontainer/` or install node.js and yarn (npm should work too).
2. define an environment variable called `REACT_APP_MAPBOX_TOKEN` with your Mapbox token (If you don't have one, you can create it at their site).
3. run `yarn install`
4. run `yarn/npm run updateAlertHistory`
5. and finally run `yarn/npm start` for development and `yarn/npm run build` for prod.

**Comment by xFlum3** [comment]
1. Where should i define REACT_APP_MAPBOX_TOKEN in my windows pc ?
Can i maybe talk with you on discord to solve it faster?

**Comment by xFlum3** [comment]
I forked your repo and make an github page like you did https://xflum3.github.io/israel-alerts-map/, my question is this site will be updated in real time ?

**Comment by kerero** [comment]
> 1. Where should i define REACT_APP_MAPBOX_TOKEN in my windows pc ?

I use a `.env` file.



> I forked your repo and make an github page like you did https://xflum3.github.io/israel-alerts-map/, my question is this site will be updated in real time ?

No. Check out the [README](https://github.com/kerero/israel-alerts-map#alerts-data) you'll see why.
Basically, you should use `npm run updateAlertHistory` to update the alert data locally, and then use `npm run deploy` to push the site to GitHub pages.

**Comment by xFlum3** [comment]
This is my discord: xflume
Can you please talk to me there and solve it with me?

**Comment by kerero** [comment]
No, I do not feel comfortable doing that.
However, you are welcome to describe your issue in more details here, and I will do my best to help.

**Comment by xFlum3** [comment]
> No, I do not feel comfortable doing that.
> 
> However, you are welcome to describe your issue in more details here, and I will do my best to help.

As I said I forked the repo and make an GitHub page for the repo so the site working but I want to know how to update the statistics that it will show real time results, if there is no option so I would like to know how can I install it on my pc with .env file and get token because mapbox want credit card for token api

**Comment by kerero** [comment]
>I want to know how to update the statistics that it will show real time results

The APIs from which the data is collected are limited to Israel + you will need a proper backend server.
So you cannot update the alerts data in real time.
You need to run `npm run updateAlertHistory` to update it before pushing the site to GH pages.


> I would like to know how can I install it on my pc with .env file and get token because mapbox want credit card for token api

I created my token more than a year ago, so maybe they changed their offering.
When I last checked, There was a free tier with limited use. And that is what I am using.

If you succeed to create your token, put the .env file in the root folder of the repo.
It should look something like this:

`/.env`:
```.env
REACT_APP_MAPBOX_TOKEN=<YOUR TOKEN>
```
